[package]
name = "salty"
version = "0.0.0"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
description = "Small sweet Ed25519 for microcontrollers"
repository = "https://github.com/nickray/salty"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["no-std", "NaCl"]

[dependencies]
# byteorder = { version = "1.3.2", default-features = false }
subtle = "2.2.1"
# subtle = { path = "../subtle" }
# subtle = { git = "https://github.com/nickray/subtle.git", branch = "clone-wars" }

[build-dependencies]
cc = "1.0"
# bindgen = "0.49.3"

[features]
default = ["tweetnacl"]
# field-impl-fallback = ["tweetnacl"]
tweetnacl = []

[profile.release]
codegen-units = 1
debug = true
lto = true
# opt-level = "s"
