[package]
name = "salty"
version = "0.0.1"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
description = "Small, sweet, swift Ed25519 signatures for microcontrollers"
repository = "https://github.com/nickray/salty"
license = "Apache-2.0 OR MIT"
readme = "README.md"
keywords = ["no-std", "NaCl", "cryptography", "signatures"]

[dependencies]
subtle = { version = "2.2", default-features = false }

[build-dependencies]
cbindgen = { version = "0.9", optional = true }

[dev-dependencies]

[features]
field-implementation = []
tweetnacl = ["field-implementation"]
haase = ["field-implementation"]
c-api =["cbindgen"]
