[package]
name = "salty"
version = "0.0.1"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
description = "Small sweet Ed25519 for microcontrollers"
repository = "https://github.com/nickray/salty"
license = "Apache-2.0 OR MIT"
readme = "README.md"
keywords = ["no-std", "NaCl", "cryptography", "signatures"]

[dependencies]
subtle = { version = "2.2", default-features = false }

[build-dependencies]
cc = { version = "1.0", optional = true }
bindgen = { version = "0.51", optional = true }
cbindgen = { version = "0.9", optional = true }

[dev-dependencies]

[features]
default = []
field-implementation = []
tweetnacl = ["field-implementation"]
haase = ["cc", "bindgen", "field-implementation"]
c-api =["cbindgen"]

[profile.release]
codegen-units = 1
debug = true
lto = true
