[build]
  command = "curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env && cargo doc --document-private-items"
  publish = "target/doc"

[[redirects]]
  from = "/"
  to = "/salty"
