version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout

      - restore_cache:
          key: project-cache

      - run:
          name: Prepare build
          command: make rustup

      - run:
          name: Build the library with debug profile
          command: make build-debug

      - run:
          name: Build the library with release profile
          command: make build-release

      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
